apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: q9coj5gpq-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/q9coj5gpq-java-quarkus-gitops